// Classroom set: francophone + common A1–A2 countries.
// mapX / mapY are percentages on the stylized world board.
export const COUNTRIES = [
  {
    id: "france",
    articleName: "la France",
    flag: "🇫🇷",
    code: "fr",
    nationalityM: "français",
    nationalityF: "française",
    mapX: 48.5,
    mapY: 36,
    aliases: ["france", "la france"],
  },
  {
    id: "belgique",
    articleName: "la Belgique",
    flag: "🇧🇪",
    code: "be",
    nationalityM: "belge",
    nationalityF: "belge",
    mapX: 49.2,
    mapY: 33.5,
    aliases: ["belgique", "la belgique"],
  },
  {
    id: "suisse",
    articleName: "la Suisse",
    flag: "🇨🇭",
    code: "ch",
    nationalityM: "suisse",
    nationalityF: "suisse",
    mapX: 50.2,
    mapY: 37,
    aliases: ["suisse", "la suisse"],
  },
  {
    id: "canada",
    articleName: "le Canada",
    flag: "🇨🇦",
    code: "ca",
    nationalityM: "canadien",
    nationalityF: "canadienne",
    mapX: 22,
    mapY: 28,
    aliases: ["canada", "le canada"],
  },
  {
    id: "senegal",
    articleName: "le Sénégal",
    flag: "🇸🇳",
    code: "sn",
    nationalityM: "sénégalais",
    nationalityF: "sénégalaise",
    mapX: 43.5,
    mapY: 52,
    aliases: ["senegal", "sénégal", "le senegal", "le sénégal"],
  },
  {
    id: "maroc",
    articleName: "le Maroc",
    flag: "🇲🇦",
    code: "ma",
    nationalityM: "marocain",
    nationalityF: "marocaine",
    mapX: 45.5,
    mapY: 46.5,
    aliases: ["maroc", "le maroc"],
  },
  {
    id: "algerie",
    articleName: "l’Algérie",
    flag: "🇩🇿",
    code: "dz",
    nationalityM: "algérien",
    nationalityF: "algérienne",
    mapX: 48.5,
    mapY: 47,
    aliases: ["algerie", "algérie", "l algerie", "l’algérie", "l'algérie", "lalgerie"],
  },
  {
    id: "tunisie",
    articleName: "la Tunisie",
    flag: "🇹🇳",
    code: "tn",
    nationalityM: "tunisien",
    nationalityF: "tunisienne",
    mapX: 51,
    mapY: 45,
    aliases: ["tunisie", "la tunisie"],
  },
  {
    id: "cote-divoire",
    articleName: "la Côte d’Ivoire",
    flag: "🇨🇮",
    code: "ci",
    nationalityM: "ivoirien",
    nationalityF: "ivoirienne",
    mapX: 44.5,
    mapY: 55.5,
    aliases: [
      "cote divoire",
      "côte d’ivoire",
      "cote d'ivoire",
      "côte d'ivoire",
      "la cote divoire",
      "la côte d’ivoire",
      "la cote d'ivoire",
      "ivoire",
    ],
  },
  {
    id: "espagne",
    articleName: "l’Espagne",
    flag: "🇪🇸",
    code: "es",
    nationalityM: "espagnol",
    nationalityF: "espagnole",
    mapX: 45.8,
    mapY: 41,
    aliases: ["espagne", "l espagne", "l’espagne", "l'espagne", "lespagne"],
  },
  {
    id: "italie",
    articleName: "l’Italie",
    flag: "🇮🇹",
    code: "it",
    nationalityM: "italien",
    nationalityF: "italienne",
    mapX: 51,
    mapY: 40.5,
    aliases: ["italie", "l italie", "l’italie", "l'italie", "litalie"],
  },
  {
    id: "allemagne",
    articleName: "l’Allemagne",
    flag: "🇩🇪",
    code: "de",
    nationalityM: "allemand",
    nationalityF: "allemande",
    mapX: 50.5,
    mapY: 34.5,
    aliases: ["allemagne", "l allemagne", "l’allemagne", "l'allemagne", "lallemagne"],
  },
  {
    id: "portugal",
    articleName: "le Portugal",
    flag: "🇵🇹",
    code: "pt",
    nationalityM: "portugais",
    nationalityF: "portugaise",
    mapX: 44.2,
    mapY: 42,
    aliases: ["portugal", "le portugal"],
  },
  {
    id: "royaume-uni",
    articleName: "le Royaume-Uni",
    flag: "🇬🇧",
    code: "gb",
    nationalityM: "britannique",
    nationalityF: "britannique",
    mapX: 46.2,
    mapY: 32.5,
    aliases: [
      "royaume-uni",
      "royaume uni",
      "le royaume-uni",
      "le royaume uni",
      "angleterre",
      "uk",
      "grande-bretagne",
      "grande bretagne",
    ],
  },
  {
    id: "etats-unis",
    articleName: "les États-Unis",
    flag: "🇺🇸",
    code: "us",
    nationalityM: "américain",
    nationalityF: "américaine",
    mapX: 18,
    mapY: 40,
    aliases: [
      "etats-unis",
      "états-unis",
      "etats unis",
      "états unis",
      "les etats-unis",
      "les états-unis",
      "usa",
      "us",
      "amerique",
      "amérique",
    ],
  },
  {
    id: "mexique",
    articleName: "le Mexique",
    flag: "🇲🇽",
    code: "mx",
    nationalityM: "mexicain",
    nationalityF: "mexicaine",
    mapX: 14.5,
    mapY: 48,
    aliases: ["mexique", "le mexique"],
  },
  {
    id: "bresil",
    articleName: "le Brésil",
    flag: "🇧🇷",
    code: "br",
    nationalityM: "brésilien",
    nationalityF: "brésilienne",
    mapX: 28,
    mapY: 62,
    aliases: ["bresil", "brésil", "le bresil", "le brésil"],
  },
  {
    id: "argentine",
    articleName: "l’Argentine",
    flag: "🇦🇷",
    code: "ar",
    nationalityM: "argentin",
    nationalityF: "argentine",
    mapX: 26,
    mapY: 76,
    aliases: ["argentine", "l argentine", "l’argentine", "l'argentine", "largentine"],
  },
  {
    id: "japon",
    articleName: "le Japon",
    flag: "🇯🇵",
    code: "jp",
    nationalityM: "japonais",
    nationalityF: "japonaise",
    mapX: 83,
    mapY: 40,
    aliases: ["japon", "le japon"],
  },
  {
    id: "chine",
    articleName: "la Chine",
    flag: "🇨🇳",
    code: "cn",
    nationalityM: "chinois",
    nationalityF: "chinoise",
    mapX: 74,
    mapY: 42,
    aliases: ["chine", "la chine"],
  },
  {
    id: "inde",
    articleName: "l’Inde",
    flag: "🇮🇳",
    code: "in",
    nationalityM: "indien",
    nationalityF: "indienne",
    mapX: 69,
    mapY: 50,
    aliases: ["inde", "l inde", "l’inde", "l'inde", "linde"],
  },
  {
    id: "australie",
    articleName: "l’Australie",
    flag: "🇦🇺",
    code: "au",
    nationalityM: "australien",
    nationalityF: "australienne",
    mapX: 82,
    mapY: 72,
    aliases: ["australie", "l australie", "l’australie", "l'australie", "laustralie"],
  },
  {
    id: "grece",
    articleName: "la Grèce",
    flag: "🇬🇷",
    code: "gr",
    nationalityM: "grec",
    nationalityF: "grecque",
    mapX: 53.5,
    mapY: 42.5,
    aliases: ["grece", "grèce", "la grece", "la grèce"],
  },
  {
    id: "pays-bas",
    articleName: "les Pays-Bas",
    flag: "🇳🇱",
    code: "nl",
    nationalityM: "néerlandais",
    nationalityF: "néerlandaise",
    mapX: 48.8,
    mapY: 32.8,
    aliases: [
      "pays-bas",
      "pays bas",
      "les pays-bas",
      "les pays bas",
      "hollande",
      "la hollande",
    ],
  },
];

export const COUNTRY_BY_ID = Object.fromEntries(
  COUNTRIES.map((country) => [country.id, country]),
);
export const COUNTRY_IDS = COUNTRIES.map((country) => country.id);

export function nationalityLabel(country) {
  if (country.nationalityM === country.nationalityF) {
    return country.nationalityM;
  }
  return `${country.nationalityM} / ${country.nationalityF}`;
}
