// 24 countries: francophone + common A1-A2 French curriculum.
// mapX / mapY are percentages on the stylized world map (0-100).
// Each country includes its grammatical French article, both genders of nationality,
// map pin coordinates, label offset direction, and surrounding perimeter placement.

export const COUNTRIES = [
  // --- TOP ROW: Northern & Western Europe / North America (6) ---
  {
    id: "canada",
    articleName: "le Canada",
    article: "le",
    name: "Canada",
    gender: "m",
    flag: "🇨🇦",
    code: "ca",
    nationalityM: "canadien",
    nationalityF: "canadienne",
    mapX: 23,
    mapY: 26,
    labelOffset: "top",
    position: "top",
    capital: "Ottawa",
    aliases: ["canada", "le canada"],
  },
  {
    id: "royaume-uni",
    articleName: "le Royaume-Uni",
    article: "le",
    name: "Royaume-Uni",
    gender: "m",
    flag: "🇬🇧",
    code: "gb",
    nationalityM: "britannique",
    nationalityF: "britannique",
    mapX: 45.8,
    mapY: 29.5,
    labelOffset: "top-left",
    position: "top",
    capital: "Londres",
    aliases: [
      "royaume-uni",
      "royaume uni",
      "le royaume-uni",
      "le royaume uni",
      "angleterre",
      "l angleterre",
      "l'angleterre",
      "l’angleterre",
      "uk",
      "grande-bretagne",
      "grande bretagne",
      "anglais",
      "anglaise",
    ],
  },
  {
    id: "pays-bas",
    articleName: "les Pays-Bas",
    article: "les",
    name: "Pays-Bas",
    gender: "pl",
    flag: "🇳🇱",
    code: "nl",
    nationalityM: "néerlandais",
    nationalityF: "néerlandaise",
    mapX: 48.6,
    mapY: 29,
    labelOffset: "top",
    position: "top",
    capital: "Amsterdam",
    aliases: [
      "pays-bas",
      "pays bas",
      "les pays-bas",
      "les pays bas",
      "hollande",
      "la hollande",
      "hollandais",
      "hollandaise",
    ],
  },
  {
    id: "belgique",
    articleName: "la Belgique",
    article: "la",
    name: "Belgique",
    gender: "f",
    flag: "🇧🇪",
    code: "be",
    nationalityM: "belge",
    nationalityF: "belge",
    mapX: 48.2,
    mapY: 32.5,
    labelOffset: "top-right",
    position: "top",
    capital: "Bruxelles",
    aliases: ["belgique", "la belgique"],
  },
  {
    id: "allemagne",
    articleName: "l’Allemagne",
    article: "l’",
    name: "Allemagne",
    gender: "f",
    flag: "🇩🇪",
    code: "de",
    nationalityM: "allemand",
    nationalityF: "allemande",
    mapX: 50.8,
    mapY: 31.5,
    labelOffset: "top-right",
    position: "top",
    capital: "Berlin",
    aliases: ["allemagne", "l allemagne", "l’allemagne", "l'allemagne", "lallemagne"],
  },
  {
    id: "suisse",
    articleName: "la Suisse",
    article: "la",
    name: "Suisse",
    gender: "f",
    flag: "🇨🇭",
    code: "ch",
    nationalityM: "suisse",
    nationalityF: "suisse",
    mapX: 49.8,
    mapY: 36,
    labelOffset: "right",
    position: "top",
    capital: "Berne",
    aliases: ["suisse", "la suisse"],
  },

  // --- RIGHT COLUMN: East, Asia & Oceania (6) ---
  {
    id: "grece",
    articleName: "la Grèce",
    article: "la",
    name: "Grèce",
    gender: "f",
    flag: "🇬🇷",
    code: "gr",
    nationalityM: "grec",
    nationalityF: "grecque",
    mapX: 54.5,
    mapY: 42.5,
    labelOffset: "right",
    position: "right",
    capital: "Athènes",
    aliases: ["grece", "grèce", "la grece", "la grèce"],
  },
  {
    id: "chine",
    articleName: "la Chine",
    article: "la",
    name: "Chine",
    gender: "f",
    flag: "🇨🇳",
    code: "cn",
    nationalityM: "chinois",
    nationalityF: "chinoise",
    mapX: 75,
    mapY: 39,
    labelOffset: "top",
    position: "right",
    capital: "Pékin",
    aliases: ["chine", "la chine"],
  },
  {
    id: "japon",
    articleName: "le Japon",
    article: "le",
    name: "Japon",
    gender: "m",
    flag: "🇯🇵",
    code: "jp",
    nationalityM: "japonais",
    nationalityF: "japonaise",
    mapX: 85.5,
    mapY: 38,
    labelOffset: "right",
    position: "right",
    capital: "Tokyo",
    aliases: ["japon", "le japon"],
  },
  {
    id: "inde",
    articleName: "l’Inde",
    article: "l’",
    name: "Inde",
    gender: "f",
    flag: "🇮🇳",
    code: "in",
    nationalityM: "indien",
    nationalityF: "indienne",
    mapX: 68.5,
    mapY: 49,
    labelOffset: "bottom",
    position: "right",
    capital: "New Delhi",
    aliases: ["inde", "l inde", "l’inde", "l'inde", "linde"],
  },
  {
    id: "australie",
    articleName: "l’Australie",
    article: "l’",
    name: "Australie",
    gender: "f",
    flag: "🇦🇺",
    code: "au",
    nationalityM: "australien",
    nationalityF: "australienne",
    mapX: 83.5,
    mapY: 74,
    labelOffset: "bottom",
    position: "right",
    capital: "Canberra",
    aliases: ["australie", "l australie", "l’australie", "l'australie", "laustralie"],
  },
  {
    id: "tunisie",
    articleName: "la Tunisie",
    article: "la",
    name: "Tunisie",
    gender: "f",
    flag: "🇹🇳",
    code: "tn",
    nationalityM: "tunisien",
    nationalityF: "tunisienne",
    mapX: 51.2,
    mapY: 45.5,
    labelOffset: "top-right",
    position: "right",
    capital: "Tunis",
    aliases: ["tunisie", "la tunisie"],
  },

  // --- BOTTOM ROW: Africa & South America (6) ---
  {
    id: "algerie",
    articleName: "l’Algérie",
    article: "l’",
    name: "Algérie",
    gender: "f",
    flag: "🇩🇿",
    code: "dz",
    nationalityM: "algérien",
    nationalityF: "algérienne",
    mapX: 48.2,
    mapY: 48,
    labelOffset: "bottom",
    position: "bottom",
    capital: "Alger",
    aliases: ["algerie", "algérie", "l algerie", "l’algérie", "l'algérie", "lalgerie"],
  },
  {
    id: "maroc",
    articleName: "le Maroc",
    article: "le",
    name: "Maroc",
    gender: "m",
    flag: "🇲🇦",
    code: "ma",
    nationalityM: "marocain",
    nationalityF: "marocaine",
    mapX: 44.5,
    mapY: 47,
    labelOffset: "left",
    position: "bottom",
    capital: "Rabat",
    aliases: ["maroc", "le maroc"],
  },
  {
    id: "senegal",
    articleName: "le Sénégal",
    article: "le",
    name: "Sénégal",
    gender: "m",
    flag: "🇸🇳",
    code: "sn",
    nationalityM: "sénégalais",
    nationalityF: "sénégalaise",
    mapX: 41.5,
    mapY: 54.5,
    labelOffset: "left",
    position: "bottom",
    capital: "Dakar",
    aliases: ["senegal", "sénégal", "le senegal", "le sénégal"],
  },
  {
    id: "cote-divoire",
    articleName: "la Côte d’Ivoire",
    article: "la",
    name: "Côte d’Ivoire",
    gender: "f",
    flag: "🇨🇮",
    code: "ci",
    nationalityM: "ivoirien",
    nationalityF: "ivoirienne",
    mapX: 44.5,
    mapY: 58.5,
    labelOffset: "bottom",
    position: "bottom",
    capital: "Yamoussoukro",
    aliases: [
      "cote divoire",
      "côte d’ivoire",
      "cote d'ivoire",
      "côte d'ivoire",
      "la cote divoire",
      "la côte d’ivoire",
      "la cote d'ivoire",
      "ivoire",
    ],
  },
  {
    id: "argentine",
    articleName: "l’Argentine",
    article: "l’",
    name: "Argentine",
    gender: "f",
    flag: "🇦🇷",
    code: "ar",
    nationalityM: "argentin",
    nationalityF: "argentine",
    mapX: 27,
    mapY: 80,
    labelOffset: "left",
    position: "bottom",
    capital: "Buenos Aires",
    aliases: ["argentine", "l argentine", "l’argentine", "l'argentine", "largentine"],
  },
  {
    id: "bresil",
    articleName: "le Brésil",
    article: "le",
    name: "Brésil",
    gender: "m",
    flag: "🇧🇷",
    code: "br",
    nationalityM: "brésilien",
    nationalityF: "brésilienne",
    mapX: 31.5,
    mapY: 66,
    labelOffset: "right",
    position: "bottom",
    capital: "Brasília",
    aliases: ["bresil", "brésil", "le bresil", "le brésil"],
  },

  // --- LEFT COLUMN: Americas & Latin Europe (6) ---
  {
    id: "etats-unis",
    articleName: "les États-Unis",
    article: "les",
    name: "États-Unis",
    gender: "pl",
    flag: "🇺🇸",
    code: "us",
    nationalityM: "américain",
    nationalityF: "américaine",
    mapX: 18.5,
    mapY: 37,
    labelOffset: "bottom",
    position: "left",
    capital: "Washington",
    aliases: [
      "etats-unis",
      "états-unis",
      "etats unis",
      "états unis",
      "les etats-unis",
      "les états-unis",
      "usa",
      "us",
      "amerique",
      "amérique",
      "l amerique",
      "l'amerique",
      "l’amerique",
    ],
  },
  {
    id: "mexique",
    articleName: "le Mexique",
    article: "le",
    name: "Mexique",
    gender: "m",
    flag: "🇲🇽",
    code: "mx",
    nationalityM: "mexicain",
    nationalityF: "mexicaine",
    mapX: 15,
    mapY: 47.5,
    labelOffset: "bottom",
    position: "left",
    capital: "Mexico",
    aliases: ["mexique", "le mexique"],
  },
  {
    id: "portugal",
    articleName: "le Portugal",
    article: "le",
    name: "Portugal",
    gender: "m",
    flag: "🇵🇹",
    code: "pt",
    nationalityM: "portugais",
    nationalityF: "portugaise",
    mapX: 43,
    mapY: 41,
    labelOffset: "left",
    position: "left",
    capital: "Lisbonne",
    aliases: ["portugal", "le portugal"],
  },
  {
    id: "espagne",
    articleName: "l’Espagne",
    article: "l’",
    name: "Espagne",
    gender: "f",
    flag: "🇪🇸",
    code: "es",
    nationalityM: "espagnol",
    nationalityF: "espagnole",
    mapX: 45,
    mapY: 41,
    labelOffset: "bottom-left",
    position: "left",
    capital: "Madrid",
    aliases: ["espagne", "l espagne", "l’espagne", "l'espagne", "lespagne"],
  },
  {
    id: "france",
    articleName: "la France",
    article: "la",
    name: "France",
    gender: "f",
    flag: "🇫🇷",
    code: "fr",
    nationalityM: "français",
    nationalityF: "française",
    mapX: 47.2,
    mapY: 35.5,
    labelOffset: "bottom-left",
    position: "left",
    capital: "Paris",
    aliases: ["france", "la france"],
  },
  {
    id: "italie",
    articleName: "l’Italie",
    article: "l’",
    name: "Italie",
    gender: "f",
    flag: "🇮🇹",
    code: "it",
    nationalityM: "italien",
    nationalityF: "italienne",
    mapX: 51.5,
    mapY: 41,
    labelOffset: "bottom-right",
    position: "left",
    capital: "Rome",
    aliases: ["italie", "l italie", "l’italie", "l'italie", "litalie"],
  },
];

export const COUNTRY_BY_ID = Object.fromEntries(
  COUNTRIES.map((country) => [country.id, country]),
);

export const COUNTRY_IDS = COUNTRIES.map((country) => country.id);

export function nationalityLabel(country) {
  if (country.nationalityM === country.nationalityF) {
    return country.nationalityM;
  }
  return `${country.nationalityM} / ${country.nationalityF}`;
}

export function formatGenderDisplay(country) {
  const isInvariant = country.nationalityM === country.nationalityF;
  return {
    isInvariant,
    m: country.nationalityM,
    f: country.nationalityF,
  };
}

export const COUNTRIES_BY_POSITION = {
  top: COUNTRIES.filter((c) => c.position === "top"),
  right: COUNTRIES.filter((c) => c.position === "right"),
  bottom: COUNTRIES.filter((c) => c.position === "bottom"),
  left: COUNTRIES.filter((c) => c.position === "left"),
};
